<a href="https://colab.research.google.com/github/lerikoder/ExData_Plotting1/blob/master/A_Repaso_de_Random.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import numpy.random as npra
#dir(np)
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : number, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : number
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off affects the length of `out`.
   

In [0]:
np.arange(23, 56)

array([23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
       40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55])

In [0]:
#help(npra.random)
A = np.ceil(npra.random_sample((130,130))*7)
x = -6 + np.ceil(npra.random_sample(130) * 6)
b = np.linalg.solve(A,x)
print("\nA= \n", A, "\nx = ", x, "\n b=", b)



A= 
 [[5. 6. 3. ... 7. 1. 4.]
 [6. 7. 1. ... 2. 7. 4.]
 [5. 5. 1. ... 6. 4. 4.]
 ...
 [2. 2. 7. ... 6. 2. 3.]
 [6. 5. 4. ... 3. 5. 3.]
 [6. 4. 5. ... 7. 1. 2.]] 
x =  [-2. -3. -2. -3. -1. -4. -1. -3.  0. -5. -5. -4. -5. -3. -2. -3. -1. -1.
 -5. -1. -1. -4. -3.  0. -1. -3. -5. -5. -2. -2.  0. -5. -5. -5. -5.  0.
 -5. -5. -1. -2. -1. -5. -5. -5. -1. -2. -2. -4. -5. -3. -3. -1. -1. -5.
 -2. -3. -2. -3. -3. -1. -2.  0.  0. -1. -5.  0. -3.  0. -2. -1.  0. -3.
 -5. -4.  0. -5. -4.  0. -4.  0. -1. -5. -3. -3. -2. -5. -2. -4. -1.  0.
 -1. -4. -5. -3.  0. -1. -5. -3. -2. -4.  0. -3.  0.  0. -4. -3. -1. -5.
 -2. -2. -3. -4. -5. -4. -1. -1. -4. -2. -2.  0. -4. -4. -2. -4.  0. -1.
 -5. -2. -3. -3.] 
 b= [-1.23119179 -0.28846817  0.94287418 -4.14308884 -4.14657473  1.51890886
 -1.9999666   0.28219745  1.38652175  0.54156586 -4.0215916   3.28103729
  2.49926099 -4.89578627 -0.79623805  0.24814847  1.70747488  1.62851145
  4.78499073  2.6572708  -0.33327087  1.27639456  0.02557916 -2.81389535
  0.28

In [0]:
print(np.matmul(A, b), "\n", x)

[-2.00000000e+00 -3.00000000e+00 -2.00000000e+00 -3.00000000e+00
 -1.00000000e+00 -4.00000000e+00 -1.00000000e+00 -3.00000000e+00
  7.10542736e-15 -5.00000000e+00 -5.00000000e+00 -4.00000000e+00
 -5.00000000e+00 -3.00000000e+00 -2.00000000e+00 -3.00000000e+00
 -1.00000000e+00 -1.00000000e+00 -5.00000000e+00 -1.00000000e+00
 -1.00000000e+00 -4.00000000e+00 -3.00000000e+00 -1.27897692e-13
 -1.00000000e+00 -3.00000000e+00 -5.00000000e+00 -5.00000000e+00
 -2.00000000e+00 -2.00000000e+00 -2.84217094e-14 -5.00000000e+00
 -5.00000000e+00 -5.00000000e+00 -5.00000000e+00  9.23705556e-14
 -5.00000000e+00 -5.00000000e+00 -1.00000000e+00 -2.00000000e+00
 -1.00000000e+00 -5.00000000e+00 -5.00000000e+00 -5.00000000e+00
 -1.00000000e+00 -2.00000000e+00 -2.00000000e+00 -4.00000000e+00
 -5.00000000e+00 -3.00000000e+00 -3.00000000e+00 -1.00000000e+00
 -1.00000000e+00 -5.00000000e+00 -2.00000000e+00 -3.00000000e+00
 -2.00000000e+00 -3.00000000e+00 -3.00000000e+00 -1.00000000e+00
 -2.00000000e+00 -1.13686